# Header
menu:
  Home: /
  Archives: /archives
  Portfolio: http://jyntran.ca
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: http://jyntran.ca/assets/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# Feed
feed:
  type: atom
  path: atom.xml
  limit: 20
